<!-- produced via tools/or_review.py | model: google/gemini-3.1-pro-preview | two-pass blind protocol | gates run by maintainer | pass-1 (blind) preserved at reviews/2026-07-gemini-gov-standard.md.pass1 -->

# Review: Promotion of GOV-anchors.md from DRAFT STANDARD to STANDARD

## Verdict: PROMOTE-WITH-AMENDMENTS

You have built a rigorous, mathematically deterministic constitution. Stabilizing the governance layer before stabilizing the Books it governs is structurally sound. However, the reference verifier contains a mathematically guaranteed suicide trapdoor on key rotation, and elevating this spec to STANDARD while it relies on a moving DRAFT target creates a normative paradox. Fix the trapdoor, define your commitments, pin your dependencies, and you are ready for STANDARD.

Here is the adversarial breakdown spanning your four assigned focus areas.

---

### 1. Conformance Obligations (§7): Real or Ceremony?

**Verdict:** The obligations are technically met by the letter of the law, but the verification strategy is heavily steeped in **ceremony** over reality.

- **Obligations #1 and #2 (Verifier and Vectors):** The output of `anchor_governance.py` (22 checks) and the provision of 16 pinned fixtures correctly fulfill the formal mandate. However, testing with static vectors is "ceremony" because they capture single, isolated points in time rather than state *transitions*. Because the vectors test static states (e.g., `GV-HIJACK-MINTED-PAIR`, `GV-KEYSTATE-UNAUTH-PROFILE`), they completely missed the P0 permanent-liveness death trap (detailed in Section 4) which emerges over sequential time. 
- **Obligation #3 (Second Implementation):** `impl-go/` correctly replays 16/16 vectors and 23/23 differential tests. It fulfills the obligation, but passing static JSON vectors generated by Python means the Go code is largely just reflecting the Python's point-in-time snapshot logic rather than independently verifying temporal transitions.
- **Obligation #4 (CI `--enforce`):** Running CI with an out-of-band trust config proves the code *executes* and prevents the "unguarded exit 0" vulnerability flagged in prior phases, but since CI must inject it as a repo variable to run, it is purely operational ceremony. It proves pipeline hygiene, not decentralized security. 

*Conclusion:* The obligations are "met", but the maintainers must recognize that static-vector conformance provides a false sense of security regarding cumulative state logic. 

### 2. COHERENCE: The STANDARD-on-DRAFT Paradox

**Verdict:** The timing is a **FEATURE**, but the dependency tree is an **INCOHERENCE**.

*The Feature:* Stabilizing the constitution before the content is legally and architecturally sound. The U.S. Constitution (the process) was ratified while its laws (the governed content) evolved. You *want* the governance mechanism to reach STANDARD first, so that the future promotion of Books I-III to STANDARD is done via a stable, immutable governance mechanism rather than a DRAFT one. 

*The Incoherence:* You cannot build a castle on shifting sand. `GOV-anchors.md` explicitly lists `Warrant SPEC v0.3` as a normative dependency. Warrant v0.3 is currently marked DRAFT. If the upstream Warrant repository redefines how thresholds or Key State (§5.1) operate before finalization, your STANDARD is retrospectively broken. An IETF/W3C Standard cannot carry a normative reference to an unpinned Internet-Draft. 

**Required Amendment (P1):**
`GOV-anchors.md` MUST pin its normative dependency to the exact snapshot provided in `proposals`. 

*Text Proposal for `GOV-anchors.md` Scope Guard:*
> **Normative dependency:** Warrant SPEC v0.3 **(strictly as pinned in `proposals/refs/warrant-SPEC-v0.3-snapshot.md`)** (§5.1 key state, §7 settlement, §9 multi-root).

### 3. The Definition of "STANDARD"

**Verdict:** `GOV-anchors.md` completely fails to define what the "STANDARD" label legally and technically binds the maintainers to. Furthermore, applying the label during `v0.6.4` violates the project's own `ROADMAP.md`, which states: *"`v0.x.y` — draft standard... `v1.0.0` — first stable release."*

If this moves to STANDARD, the maintainers must irrevocably commit to specific backward-compatibility guarantees. A mere label change without an SLA is meaningless.

**Required Amendments (P1/P2):**
1. **Version Independence:** To respect the ROADMAP and project hygiene, `GOV-anchors.md` should be bumped to `Version: 1.0.0` (even while carried within repo release bundle `v0.6.4`).
2. **Commitment Clause:** Insert a new section into `GOV-anchors.md` definitively stating what the STANDARD label guarantees.

*Text Proposal for `GOV-anchors.md` (New Section after Status):*
> **Standard Commitments:** By bearing the STANDARD designation, this document guarantees that: (1) The schemas `sigma-glyph.anchor-set@v1` and `sigma-glyph.anchor-governance@v1` are frozen; no breaking changes will occur without migrating to `@v2` tags. (2) The policy lineage derivation algorithm (§3) is locked; any future mechanical changes to settlement will require an explicit fork to a new Genesis Root Jurisdiction.

### 4. Required Blocker: The Suicide Verifier (P0)

**Verdict:** DO NOT PROMOTE until `tools/anchor_governance.py` is fixed. The current implementation contains a mathematically guaranteed suicide trapdoor on key rotation.

If an actor gets compromised and legitimately publishes a quorum-authorized key-state warrant (whether `accept` or `supersede`) to rotate their key, the `key_state_under_governance` function in your reference verifier spots it. It then causes `verify_adoption` to abort entirely with:
`ERR: key-state warrants under governance policy — derive key state with the warrant CLI first`

**The Arithmetic of the Deadlock:**
Let $S$ be the cumulative settlement closure DAG (Warrant §9 descendant closure from genesis).
1. At $T_0$, an actor rotates a key. A key-state warrant $W_{ks}$ is settled. $W_{ks} \in S$.
2. The verifier checks $S$, finds $W_{ks}$, and throws the fatal error advising manual derivation.
3. At $T_1$, the admin follows the instructions, uses the Warrant CLI, and correctly updates the out-of-band `trust-config.json` with the new key.
4. The admin runs the verifier again. Because the closure $S$ is immutable and historical, $W_{ks}$ is *still* in $S$. The script parses the closure, spots $W_{ks}$, and throws the fatal error again.
5. CI is permanently red. The governance chain is deadlocked. No future releases can ever be authorized without hard-forking to a new genesis root.

**The Fix:**
The out-of-band trust config must be given a mechanism to explicitly acknowledge up to what point key-state has been resolved manually so the verifier knows to skip it. 

*Patch Proposal for `anchor_governance.py`* checking `trust_config` limits:
1. Update `valid_trust` to permit an optional array: `"resolved_key_state": ["<WarrantID>"]`.
2. Update `key_state_under_governance` to bypass records the user has already absorbed:
```python
        if rid in trust.get("resolved_key_state", []):
            continue
```
This forces the user to manually derive the key, update the `actors` mapping with the new key, AND add the `rid` of the key-state warrant to `resolved_key_state` in the config. The verifier can then safely resume operation.

---

## Relation to Prior Reviews

*Attribution note: All operational/historical details about code behavior or prior system states are drawn exclusively from the provided review transcripts (GPT-5, Gemini, DeepSeek, Codex) and their respective maintainer responses.* 

### Agreement with Codex (v0.6.0 Pedantic Audit): Strict Version/Bundle Hygiene
I strongly agree with Codex's previous findings regarding document-version vs. bundle-version ambiguities. Codex rightly pointed out that per-document headers MUST reflect their individual status distinct from the master repository release. 
**New Perspective:** I am extending Codex's logic directly to my FOCUS Section 3 finding. If `GOV-anchors.md` is promoted to STANDARD, it must carry `Version: 1.0.0` internally to respect the project's ROADMAP maturity definitions, even if the surrounding repository bundle is heavily `v0.x.y` draft-state.

### Agreement with GPT-5 (ADR-007 Gate): Lineage Solidification
GPT-5's §3 finding heavily pushed for the lineage binding (profile hash-pins the threshold; exactly one profile + one threshold). The maintainer accepted this and locked down the current-profile derivation. 
**New Perspective:** My Section 3 text proposal ("Commitment Clause") specifically leverages GPT-5's mechanism. If GOV is to be "STANDARD," the maintainers must guarantee that the lineage derivation algorithm implemented via GPT-5's advice is now irrevocably locked.

### Disagreement with Maintainers, Gemini, and DeepSeek (ADR-007 Gate): The Key-State Trapdoor
During the ADR-007 review, both Gemini (Vulnerability C) and DeepSeek (§6.5) warned that `anchor_governance.py` aborting on key-state warrants was a fatal CI flaw. DeepSeek correctly pointed out this was too broad and bricked unrelated chains. 
*The maintainer's response at the time stated they were partially accepting this by scoping the refusal ONLY to key-state warrants filed under the governance policy blob, writing: "The remaining refusal is kept deliberately: this is a scoped verifier and silent mis-binding is worse than a loud handoff to the warrant CLI."*

**Argument / Disagreement:** I definitively disagree with the maintainer's decision to retain the "loud handoff" within the scoped GOV path, and I am pushing the critique significantly further than Gemini or DeepSeek did. Gemini and DeepSeek focused on the blast radius to *unrelated* chains. My Section 4 analysis mathematically proves that keeping the "loud handoff" for *its own governed chain* creates an unrecoverable permanent liveness lock. Because the settlement closure (the DAG) is cumulative and historical, the tool will trigger the loud handoff *infinitely* on every subsequent CI run, even after the human operator has done exactly as instructed. 

The maintainer's ADR-007 "compromise" fails to account for sequential time and state-transitions, which was exactly the blindspot I highlighted in FOCUS Section 1 regarding static snapshot conformance vectors. The mechanism MUST be patched (using my `resolved_key_state` config array) or the "STANDARD" governance module will inevitably self-destruct upon its first roster rotation.
