#!/usr/bin/env python3
"""Generate proofs/LutData.lean from the Book II oracle's LUT_COS.

The oracle's gen_lut() already FAILS FAST unless the table matches the
normative SHA-256 arbiter (Book II §4), so importing LUT_COS here inherits
that check: this file cannot be generated from a wrong table. Regeneration
is deterministic — CI enforces byte-identity like every other generated
artifact.
"""
import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "impl"))
from sigma_wave import LUT_COS, LUT_ARBITER  # noqa: E402

OUT = os.environ.get("LUT_LEAN_OUT") or os.path.join(HERE, "LutData.lean")

body = ",".join(str(v) for v in LUT_COS)

open(OUT, "w").write(f"""\
/- GENERATED by proofs/gen_lut_lean.py — do not edit.
   Book II §4 LUT_COS: 32769 entries, SHA-256 arbiter
   {LUT_ARBITER}
   (the generator imports the oracle's table, which fail-fasts on arbiter
   mismatch — this data cannot be produced from a wrong LUT).
   Encoded as one string literal: a 32769-element array literal elaborates
   quadratically and times out; the decoder runs compiled under
   `native_decide`, so LUT facts stay machine-checked. -/
namespace WaveAlgebra

def lutString : String :=
  "{body}"

def lutCos : Array Int :=
  (lutString.splitOn ",").foldl (fun a s => a.push s.toInt!) (Array.mkEmpty 32769)

end WaveAlgebra
""")
print(f"wrote {OUT} ({len(LUT_COS)} entries)")
